# The settings from this file will override the values from `docker-compose.yml`
# When run via:
#     docker compose -f docker-compose.yml -f docker-compose.development.yml

# For use on macOS:
# See: https://www.docker.com/blog/user-guided-caching-in-docker-for-mac/
# To speed up the start-up process, use: ':cached' flag on volume definitions

# For debugging:
#
# Make the service boot and wait:
#     command: "tail -f /dev/null"
#

services:
  121db:
    image: 'postgres:14'
    init: true
    container_name: 121db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DBNAME}
    volumes:
      - './postgresql.conf:/etc/postgresql.conf'
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
    ports:
      - '5438:5432'
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DBNAME}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3

  wiremock:
    image: rodolpheche/wiremock
    ports:
      - '8081:8080'
    volumes:
      - './wiremock/mappings:/home/wiremock/mappings'
      - './wiremock/__files:/home/wiremock/__files'
    command: ['--verbose', '--global-response-templating']
    container_name: wiremock

  121-service:
    build:
      target: development
    volumes:
      - './121-service:/home/node/app'
      - './121-service/Dockerfile:/home/node/app/Dockerfile'
      - './121-service/jest.json:/home/node/app/jest.json'
      - './121-service/node_modules:/home/node/app/node_modules'
      - './121-service/package-lock.json:/home/node/app/package-lock.json'
      - './121-service/src:/home/node/app/src'
      - './121-service/.dockerignore:/home/node/app/.dockerignore'
      - './121-service/LICENSE:/home/node/app/LICENSE'
      - './121-service/.node-version:/home/node/app/.node-version'
      - './121-service/.prettierignore:/home/node/app/.prettierignore'
      - './121-service/tsconfig.json:/home/node/app/tsconfig.json'
      - './121-service/appdatasource.ts:/home/node/app/appdatasource.ts'
      - './121-service/.eslintrc.js:/home/node/app/.eslintrc.js'
      - './121-service/migration:/home/node/app/migration'
      - './121-service/.nvmrc:/home/node/app/.nvmrc'
      - './121-service/.prettierrc.js:/home/node/app/.prettierrc.js'
      - './121-service/voice:/home/node/app/voice'
      - './121-service/azure-pipelines.yml:/home/node/app/azure-pipelines.yml'
      - './121-service/.gitignore:/home/node/app/.gitignore'
      - './121-service/module-dependencies.md:/home/node/app/module-dependencies.md'
      - './121-service/ormconfig.ts:/home/node/app/ormconfig.ts'
      - './121-service/README.md:/home/node/app/README.md'
      - './121-service/.vscode:/home/node/app/.vscode'
      - './121-service/dist:/home/node/app/dist'
      - './121-service/index.js:/home/node/app/index.js'
      - './121-service/nestconfig.json:/home/node/app/nestconfig.json'
      - './121-service/package.json:/home/node/app/package.json'
      - './121-service/seed-data:/home/node/app/seed-data'
      - './121-service/test:/home/node/app/test'
      - './121-service/WORKFLOWS.md:/home/node/app/WORKFLOWS.md'
